Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 18, in <module>
    designs = json.loads(response.text)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/rest_framework/utils/json.py", line 40, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 18, in <module>
    designs = json.loads(response.text)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/rest_framework/utils/json.py", line 40, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 18, in <module>
    designs = json.loads(response.text)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/rest_framework/utils/json.py", line 40, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 18, in <module>
    designs = json.loads(response.text)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/rest_framework/utils/json.py", line 40, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 18, in <module>
    designs = json.loads(response.text)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/rest_framework/utils/json.py", line 40, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 18, in <module>
    designs = json.loads(response.text)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/rest_framework/utils/json.py", line 40, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 18, in <module>
    designs = json.loads(response.text)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/rest_framework/utils/json.py", line 40, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 18, in <module>
    designs = json.loads(response.text)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/rest_framework/utils/json.py", line 40, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 18, in <module>
    designs = json.loads(response.text)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/rest_framework/utils/json.py", line 40, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 18, in <module>
    designs = json.loads(response.text)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/rest_framework/utils/json.py", line 40, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 18, in <module>
    designs = json.loads(response.text)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/rest_framework/utils/json.py", line 40, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 18, in <module>
    designs = json.loads(response.text)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/rest_framework/utils/json.py", line 40, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 18, in <module>
    designs = json.loads(response.text)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/rest_framework/utils/json.py", line 40, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 18, in <module>
    designs = json.loads(response.text)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/rest_framework/utils/json.py", line 40, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 18, in <module>
    designs = json.loads(response.text)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/rest_framework/utils/json.py", line 40, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 18, in <module>
    designs = json.loads(response.text)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/rest_framework/utils/json.py", line 40, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 18, in <module>
    designs = json.loads(response.text)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/rest_framework/utils/json.py", line 40, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 18, in <module>
    designs = json.loads(response.text)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/rest_framework/utils/json.py", line 40, in loads
    return json.loads(*args, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 11, in <module>
    django.setup()
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/ec2-user/Grupo01_env/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/Grupo01/project_1/settings.py", line 165, in <module>
    AWS_ACCESS_KEY_ID  = os.environ["EMAIL_DESIGN_KEY"]
  File "/home/ec2-user/Grupo01_env/lib64/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'EMAIL_DESIGN_KEY'
Traceback (most recent call last):
  File "/home/ec2-user/Grupo01/image_process.py", line 11, in <module>
    django.setup()
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ec2-user/Grupo01_env/local/lib/python3.6/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/ec2-user/Grupo01_env/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/Grupo01/project_1/settings.py", line 165, in <module>
    AWS_ACCESS_KEY_ID  = os.environ["EMAIL_DESIGN_KEY"]
  File "/home/ec2-user/Grupo01_env/lib64/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'EMAIL_DESIGN_KEY'
